name: Sync Content

on:
  push:
    paths:
      - 'script/tema01_Manejo_de_permisos_a_nivel_de_usuarios_de_base_de_datos/tema_Manejo _de_permisos_a_nivel_de_usuarios_de_base_de_datos.md'

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Append content
      run: |
        echo "## Tema 1" >> 3DBitStore.md
        cat "script/tema01_Manejo_de_permisos_a_nivel_de_usuarios_de_base_de_datos/tema_Manejo _de_permisos_a_nivel_de_usuarios_de_base_de_datos.md" >> 3DBitStore.md

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 3DBitStore.md
        git commit -m "Update Tema 2 section in 3DBitStore.md"
        git push
